// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transport$0 from "../transport/models.js";

/**
 * Binding captures the exact transient connection for one operation.
 */
export class Binding {
    "ID": DeviceID;
    "ProfileID": string;
    "Path": string;
    "InventoryRevision": number;

    /**
     * SessionOnly marks bindings that must never be persisted or migrated.
     */
    "SessionOnly": boolean;

    /** Creates a new Binding instance. */
    constructor($$source: Partial<Binding> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = (new DeviceID());
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("InventoryRevision" in $$source)) {
            this["InventoryRevision"] = 0;
        }
        if (!("SessionOnly" in $$source)) {
            this["SessionOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binding instance from a string or object.
     */
    static createFrom($$source: any = {}): Binding {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ID" in $$parsedSource) {
            $$parsedSource["ID"] = $$createField0_0($$parsedSource["ID"]);
        }
        return new Binding($$parsedSource as Partial<Binding>);
    }
}

export class Device {
    "ID": DeviceID;
    "Profile": string;
    "Path": string;
    "Connection": transport$0.Connection;
    "Eligible": boolean;
    "Warning": string;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = (new DeviceID());
        }
        if (!("Profile" in $$source)) {
            this["Profile"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Connection" in $$source)) {
            this["Connection"] = transport$0.Connection.$zero;
        }
        if (!("Eligible" in $$source)) {
            this["Eligible"] = false;
        }
        if (!("Warning" in $$source)) {
            this["Warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ID" in $$parsedSource) {
            $$parsedSource["ID"] = $$createField0_0($$parsedSource["ID"]);
        }
        return new Device($$parsedSource as Partial<Device>);
    }
}

/**
 * DeviceID is the stable identity for persisted device state. Path is deliberately
 * excluded because it changes when the device topology changes.
 */
export class DeviceID {
    "VendorID": number;
    "ProductID": number;
    "Serial": string;

    /** Creates a new DeviceID instance. */
    constructor($$source: Partial<DeviceID> = {}) {
        if (!("VendorID" in $$source)) {
            this["VendorID"] = 0;
        }
        if (!("ProductID" in $$source)) {
            this["ProductID"] = 0;
        }
        if (!("Serial" in $$source)) {
            this["Serial"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceID instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceID {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceID($$parsedSource as Partial<DeviceID>);
    }
}

export enum MacroAssignmentProgress {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    MacroAssignmentNotStarted = 0,
    MacroAssignmentUnknown = 1,
    MacroAssignmentACKConfirmed = 2,
};

/**
 * MacroProgress records transport evidence only, never playback or persistence.
 * Zero values explicitly mean neither phase was started.
 */
export class MacroProgress {
    "Assignment": MacroAssignmentProgress;
    "Upload": MacroUploadProgress;

    /** Creates a new MacroProgress instance. */
    constructor($$source: Partial<MacroProgress> = {}) {
        if (!("Assignment" in $$source)) {
            this["Assignment"] = MacroAssignmentProgress.$zero;
        }
        if (!("Upload" in $$source)) {
            this["Upload"] = MacroUploadProgress.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacroProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): MacroProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacroProgress($$parsedSource as Partial<MacroProgress>);
    }
}

export enum MacroUploadProgress {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    MacroUploadNotStarted = 0,
    MacroUploadPossiblyPartial = 1,
    MacroUploadConfirmed = 2,
};

/**
 * TargetedService owns inventory selection and state scoped to stable identities.
 */
export class TargetedService {

    /** Creates a new TargetedService instance. */
    constructor($$source: Partial<TargetedService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetedService instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetedService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TargetedService($$parsedSource as Partial<TargetedService>);
    }
}

// Private type creation functions
const $$createType0 = DeviceID.createFrom;
