FROM node:22-bookworm-slim AS node

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=node /usr/local /usr/local

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        build-essential \
        ca-certificates \
        desktop-file-utils \
        file \
        git \
        golang-go \
        libayatana-appindicator3-dev \
        libfuse2t64 \
        libgtk-4-dev \
        librsvg2-dev \
        libwebkitgtk-6.0-dev \
        libwebkitgtk-6.0-4 \
        nodejs \
        npm \
        pkg-config \
        squashfs-tools \
    && GOBIN=/usr/local/bin go install github.com/go-task/task/v3/cmd/task@v3.53.1 \
    && GOBIN=/usr/local/bin go install github.com/wailsapp/wails/v3/cmd/wails3@v3.0.0-beta.23 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
