// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action describes a press or release, not a firmware opcode.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Down = "down",
    Up = "up",
};

export class Event {
    "type": EventType;
    "action": Action;
    "delay_ms": number;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("type" in $$source)) {
            this["type"] = EventType.$zero;
        }
        if (!("action" in $$source)) {
            this["action"] = Action.$zero;
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event($$parsedSource as Partial<Event>);
    }
}

/**
 * EventType identifies the local input involved in an event.
 */
export enum EventType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MouseLeft = "mouse_left",
    MouseRight = "mouse_right",
    MouseMiddle = "mouse_middle",
    MouseBack = "mouse_back",
    MouseForward = "mouse_forward",
};

export class Macro {
    "id": string;
    "name": string;
    "events": Event[];

    /** Creates a new Macro instance. */
    constructor($$source: Partial<Macro> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Macro instance from a string or object.
     */
    static createFrom($$source: any = {}): Macro {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField2_0($$parsedSource["events"]);
        }
        return new Macro($$parsedSource as Partial<Macro>);
    }
}

// Private type creation functions
const $$createType0 = Event.createFrom;
const $$createType1 = $Create.Array($$createType0);
