// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PollingRate is one of the X6's supported report frequencies in hertz.
 */
export enum PollingRate {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    PollingRate125 = 125,
    PollingRate250 = 250,
    PollingRate500 = 500,
    PollingRate1000 = 1000,
};
