// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mouse$0 from "../mouse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$1 from "../protocol/x6/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$0 from "../x6/models.js";

export const Binding = mouse$0.Binding;
export type Binding = mouse$0.Binding;

export class DPIConfig {
    "AngleControl": boolean;
    "RippleControl": boolean;
    "StageMask": number;
    "LiftDistance": number;
    "DPI": number[];
    "ActiveStage": number;
    "Colors": number[][];

    /** Creates a new DPIConfig instance. */
    constructor($$source: Partial<DPIConfig> = {}) {
        if (!("AngleControl" in $$source)) {
            this["AngleControl"] = false;
        }
        if (!("RippleControl" in $$source)) {
            this["RippleControl"] = false;
        }
        if (!("StageMask" in $$source)) {
            this["StageMask"] = 0;
        }
        if (!("LiftDistance" in $$source)) {
            this["LiftDistance"] = 0;
        }
        if (!("DPI" in $$source)) {
            this["DPI"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("ActiveStage" in $$source)) {
            this["ActiveStage"] = 0;
        }
        if (!("Colors" in $$source)) {
            this["Colors"] = Array.from({ length: 8 }, () => Array.from({ length: 3 }, () => 0));
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DPIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DPIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DPIConfig($$parsedSource as Partial<DPIConfig>);
    }
}

export const Device = mouse$0.Device;
export type Device = mouse$0.Device;

export const DeviceID = mouse$0.DeviceID;
export type DeviceID = mouse$0.DeviceID;

export class Error {
    "Code": ErrorCode;

    /** Creates a new Error instance. */
    constructor($$source: Partial<Error> = {}) {
        if (!("Code" in $$source)) {
            this["Code"] = ErrorCode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Error instance from a string or object.
     */
    static createFrom($$source: any = {}): Error {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Error($$parsedSource as Partial<Error>);
    }
}

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceUnavailable = "device_unavailable",
    PermissionDenied = "permission_denied",
    StatusReadFailed = "status_read_failed",
    InvalidConfiguration = "invalid_configuration",
    ApplyFailed = "apply_failed",
    PersistenceFailed = "persistence_failed",
    SelectionRequired = "selection_required",
    StaleBinding = "stale_binding",
    AmbiguousIdentity = "ambiguous_identity",
    MigrationFailed = "migration_failed",
};

/**
 * EventSink pushes live status updates to the frontend. The desktop service
 * never imports Wails: the application wiring supplies the real emitter.
 */
export type EventSink = any;

export class Inventory {
    "Devices": Device[];
    "Selected": Binding | null;
    "Error": Error;

    /** Creates a new Inventory instance. */
    constructor($$source: Partial<Inventory> = {}) {
        if (!("Devices" in $$source)) {
            this["Devices"] = [];
        }
        if (!("Selected" in $$source)) {
            this["Selected"] = null;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Inventory instance from a string or object.
     */
    static createFrom($$source: any = {}): Inventory {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Devices" in $$parsedSource) {
            $$parsedSource["Devices"] = $$createField0_0($$parsedSource["Devices"]);
        }
        if ("Selected" in $$parsedSource) {
            $$parsedSource["Selected"] = $$createField1_0($$parsedSource["Selected"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField2_0($$parsedSource["Error"]);
        }
        return new Inventory($$parsedSource as Partial<Inventory>);
    }
}

export class LightingSnapshot {
    "Pending": x6$0.LightingSelection;
    "Applied": x6$0.LightingSelection | null;
    "Effects": x6$0.LightingEffect[];
    "Revision": number;
    "Firmware": string;
    "Error": Error;

    /** Creates a new LightingSnapshot instance. */
    constructor($$source: Partial<LightingSnapshot> = {}) {
        if (!("Pending" in $$source)) {
            this["Pending"] = (new x6$0.LightingSelection());
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = null;
        }
        if (!("Effects" in $$source)) {
            this["Effects"] = [];
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LightingSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): LightingSnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField0_0($$parsedSource["Pending"]);
        }
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField1_0($$parsedSource["Applied"]);
        }
        if ("Effects" in $$parsedSource) {
            $$parsedSource["Effects"] = $$createField2_0($$parsedSource["Effects"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField5_0($$parsedSource["Error"]);
        }
        return new LightingSnapshot($$parsedSource as Partial<LightingSnapshot>);
    }
}

export class PollingSnapshot {
    "Desired": x6$0.PollingRate;
    "Applied": x6$0.PollingRate;
    "Persisted": x6$0.PollingRate | null;
    "Factory": x6$0.PollingRate;
    "Revision": number;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;

    /** Creates a new PollingSnapshot instance. */
    constructor($$source: Partial<PollingSnapshot> = {}) {
        if (!("Desired" in $$source)) {
            this["Desired"] = x6$1.PollingRate.$zero;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = x6$1.PollingRate.$zero;
        }
        if (!("Persisted" in $$source)) {
            this["Persisted"] = null;
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = x6$1.PollingRate.$zero;
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollingSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): PollingSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollingSnapshot($$parsedSource as Partial<PollingSnapshot>);
    }
}

export class Service {

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

export class Snapshot {
    "Connection": string;
    "Battery": number | null;
    "Applied": DPIConfig;
    "Pending": DPIConfig;
    "Factory": DPIConfig;
    "Revision": number;
    "Error": Error;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;
    "ObservedStage": number | null;
    "ObservedDPI": number | null;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("Connection" in $$source)) {
            this["Connection"] = "";
        }
        if (!("Battery" in $$source)) {
            this["Battery"] = null;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = (new DPIConfig());
        }
        if (!("Pending" in $$source)) {
            this["Pending"] = (new DPIConfig());
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = (new DPIConfig());
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }
        if (!("ObservedStage" in $$source)) {
            this["ObservedStage"] = null;
        }
        if (!("ObservedDPI" in $$source)) {
            this["ObservedDPI"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType9;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField2_0($$parsedSource["Applied"]);
        }
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField3_0($$parsedSource["Pending"]);
        }
        if ("Factory" in $$parsedSource) {
            $$parsedSource["Factory"] = $$createField4_0($$parsedSource["Factory"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField6_0($$parsedSource["Error"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

/**
 * StatusListener runs the always-on status listener until its context is
 * cancelled, forwarding every dongle-pushed report through onStatus.
 */
export type StatusListener = any;

// Private type creation functions
const $$createType0 = mouse$0.Device.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = mouse$0.Binding.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Error.createFrom;
const $$createType5 = x6$1.LightingSelection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = x6$0.LightingEffect.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = DPIConfig.createFrom;
