// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum LightingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    LightingOff = 0,
    LightingFixed = 16,
    LightingBreathing = 32,
    LightingNeon = 48,
    LightingColorBreathing = 64,
    LightingStaticDPI = 80,
    LightingBreathingDPI = 96,
};

export class LightingSelection {
    "Mode": LightingMode;
    "TemplateID": LightingTemplateID;

    /** Creates a new LightingSelection instance. */
    constructor($$source: Partial<LightingSelection> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = LightingMode.$zero;
        }
        if (!("TemplateID" in $$source)) {
            this["TemplateID"] = LightingTemplateID.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LightingSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): LightingSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LightingSelection($$parsedSource as Partial<LightingSelection>);
    }
}

export enum LightingTemplateID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LightingTemplateOff = "off",
    LightingTemplateFixedGreen = "fixed-green",
    LightingTemplateBreathingGreen = "breathing-green",
    LightingTemplateBreathingFE5EF9 = "breathing-fe5ef9",
    LightingTemplateBreathingFF7F00 = "breathing-ff7f00",
    LightingTemplateBreathingFFFF00 = "breathing-ffff00",
    LightingTemplateStaticDPIDefault = "static-dpi-default",
    LightingTemplateNeonOne = "neon-one",
    LightingTemplateNeonTwo = "neon-two",
    LightingTemplateColorBreathingOne = "color-breathing-one",
    LightingTemplateColorBreathingTwo = "color-breathing-two",
    LightingTemplateBreathingDPIOne = "breathing-dpi-one",
    LightingTemplateBreathingDPITwo = "breathing-dpi-two",
    LightingTemplateBreathingDPIThree = "breathing-dpi-three",
};

/**
 * PollingRate is one of the X6's supported report frequencies in hertz.
 */
export enum PollingRate {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    PollingRate125 = 125,
    PollingRate250 = 250,
    PollingRate500 = 500,
    PollingRate1000 = 1000,
};

export enum RemapAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RemapOff = "off",
    RemapLeft = "left",
    RemapRight = "right",
    RemapMiddle = "middle",
    RemapBackward = "backward",
    RemapForward = "forward",
    RemapDoubleClick = "double_click",
    RemapFire = "fire",
};

export class RemapButton {
    "Button": number;
    "Action": RemapAction;
    "PreservedDefault": string;

    /** Creates a new RemapButton instance. */
    constructor($$source: Partial<RemapButton> = {}) {
        if (!("Button" in $$source)) {
            this["Button"] = 0;
        }
        if (!("Action" in $$source)) {
            this["Action"] = RemapAction.$zero;
        }
        if (!("PreservedDefault" in $$source)) {
            this["PreservedDefault"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemapButton instance from a string or object.
     */
    static createFrom($$source: any = {}): RemapButton {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemapButton($$parsedSource as Partial<RemapButton>);
    }
}

export class RemapConfig {
    "Buttons": RemapButton[];

    /** Creates a new RemapConfig instance. */
    constructor($$source: Partial<RemapConfig> = {}) {
        if (!("Buttons" in $$source)) {
            this["Buttons"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemapConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RemapConfig {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Buttons" in $$parsedSource) {
            $$parsedSource["Buttons"] = $$createField0_0($$parsedSource["Buttons"]);
        }
        return new RemapConfig($$parsedSource as Partial<RemapConfig>);
    }
}

// Private type creation functions
const $$createType0 = RemapButton.createFrom;
const $$createType1 = $Create.Array($$createType0);
