// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DPIConfig {
    "AngleControl": boolean;
    "RippleControl": boolean;
    "StageMask": number;
    "LiftDistance": number;
    "DPI": number[];
    "ActiveStage": number;
    "Colors": number[][];

    /** Creates a new DPIConfig instance. */
    constructor($$source: Partial<DPIConfig> = {}) {
        if (!("AngleControl" in $$source)) {
            this["AngleControl"] = false;
        }
        if (!("RippleControl" in $$source)) {
            this["RippleControl"] = false;
        }
        if (!("StageMask" in $$source)) {
            this["StageMask"] = 0;
        }
        if (!("LiftDistance" in $$source)) {
            this["LiftDistance"] = 0;
        }
        if (!("DPI" in $$source)) {
            this["DPI"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("ActiveStage" in $$source)) {
            this["ActiveStage"] = 0;
        }
        if (!("Colors" in $$source)) {
            this["Colors"] = Array.from({ length: 8 }, () => Array.from({ length: 3 }, () => 0));
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DPIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DPIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DPIConfig($$parsedSource as Partial<DPIConfig>);
    }
}

export class Error {
    "Code": ErrorCode;

    /** Creates a new Error instance. */
    constructor($$source: Partial<Error> = {}) {
        if (!("Code" in $$source)) {
            this["Code"] = ErrorCode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Error instance from a string or object.
     */
    static createFrom($$source: any = {}): Error {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Error($$parsedSource as Partial<Error>);
    }
}

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceUnavailable = "device_unavailable",
    PermissionDenied = "permission_denied",
    StatusReadFailed = "status_read_failed",
    InvalidConfiguration = "invalid_configuration",
    ApplyFailed = "apply_failed",
    PersistenceFailed = "persistence_failed",
};

export class Snapshot {
    "Connection": string;
    "Battery": number | null;
    "Applied": DPIConfig;
    "Pending": DPIConfig;
    "Factory": DPIConfig;
    "Revision": number;
    "Error": Error;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("Connection" in $$source)) {
            this["Connection"] = "";
        }
        if (!("Battery" in $$source)) {
            this["Battery"] = null;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = (new DPIConfig());
        }
        if (!("Pending" in $$source)) {
            this["Pending"] = (new DPIConfig());
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = (new DPIConfig());
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField2_0($$parsedSource["Applied"]);
        }
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField3_0($$parsedSource["Pending"]);
        }
        if ("Factory" in $$parsedSource) {
            $$parsedSource["Factory"] = $$createField6_0($$parsedSource["Factory"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField7_0($$parsedSource["Error"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

// Private type creation functions
const $$createType0 = DPIConfig.createFrom;
const $$createType1 = Error.createFrom;
