// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyDPI(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2499238003).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSnapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3468627504).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RefreshStatus(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(4154748181).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StageDPI(config: $models.DPIConfig): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(777652337, config).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Snapshot.createFrom;
