// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as macros$0 from "../macros/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mouse$0 from "../mouse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$0 from "../protocol/x6/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$1 from "../x6/models.js";

export const Binding = mouse$0.Binding;
export type Binding = mouse$0.Binding;

export class DPIConfig {
    "AngleControl": boolean;
    "RippleControl": boolean;
    "StageMask": number;
    "LiftDistance": number;
    "DPI": number[];
    "ActiveStage": number;
    "Colors": number[][];

    /** Creates a new DPIConfig instance. */
    constructor($$source: Partial<DPIConfig> = {}) {
        if (!("AngleControl" in $$source)) {
            this["AngleControl"] = false;
        }
        if (!("RippleControl" in $$source)) {
            this["RippleControl"] = false;
        }
        if (!("StageMask" in $$source)) {
            this["StageMask"] = 0;
        }
        if (!("LiftDistance" in $$source)) {
            this["LiftDistance"] = 0;
        }
        if (!("DPI" in $$source)) {
            this["DPI"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("ActiveStage" in $$source)) {
            this["ActiveStage"] = 0;
        }
        if (!("Colors" in $$source)) {
            this["Colors"] = Array.from({ length: 8 }, () => Array.from({ length: 3 }, () => 0));
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DPIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DPIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DPIConfig($$parsedSource as Partial<DPIConfig>);
    }
}

export class DebounceSnapshot {
    "Desired": number;
    "Applied": number;
    "Persisted": number | null;
    "Factory": number;
    "Revision": number;
    "Error": Error;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;

    /** Creates a new DebounceSnapshot instance. */
    constructor($$source: Partial<DebounceSnapshot> = {}) {
        if (!("Desired" in $$source)) {
            this["Desired"] = 0;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = 0;
        }
        if (!("Persisted" in $$source)) {
            this["Persisted"] = null;
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = 0;
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebounceSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): DebounceSnapshot {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField4_0($$parsedSource["Error"]);
        }
        return new DebounceSnapshot($$parsedSource as Partial<DebounceSnapshot>);
    }
}

export const Device = mouse$0.Device;
export type Device = mouse$0.Device;

export const DeviceID = mouse$0.DeviceID;
export type DeviceID = mouse$0.DeviceID;

export class Error {
    "Code": ErrorCode;

    /** Creates a new Error instance. */
    constructor($$source: Partial<Error> = {}) {
        if (!("Code" in $$source)) {
            this["Code"] = ErrorCode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Error instance from a string or object.
     */
    static createFrom($$source: any = {}): Error {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Error($$parsedSource as Partial<Error>);
    }
}

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceUnavailable = "device_unavailable",
    DeviceDisconnected = "device_disconnected",
    PermissionDenied = "permission_denied",
    StatusReadFailed = "status_read_failed",
    InvalidConfiguration = "invalid_configuration",
    ApplyFailed = "apply_failed",
    PersistenceFailed = "persistence_failed",
    SelectionRequired = "selection_required",
    StaleBinding = "stale_binding",
    AmbiguousIdentity = "ambiguous_identity",
    MigrationFailed = "migration_failed",
};

/**
 * EventSink pushes live status updates to the frontend. The desktop service
 * never imports Wails: the application wiring supplies the real emitter.
 */
export type EventSink = any;

export class Inventory {
    "Devices": Device[];
    "Selected": Binding | null;
    "Error": Error;

    /** Creates a new Inventory instance. */
    constructor($$source: Partial<Inventory> = {}) {
        if (!("Devices" in $$source)) {
            this["Devices"] = [];
        }
        if (!("Selected" in $$source)) {
            this["Selected"] = null;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Inventory instance from a string or object.
     */
    static createFrom($$source: any = {}): Inventory {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Devices" in $$parsedSource) {
            $$parsedSource["Devices"] = $$createField0_0($$parsedSource["Devices"]);
        }
        if ("Selected" in $$parsedSource) {
            $$parsedSource["Selected"] = $$createField1_0($$parsedSource["Selected"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField2_0($$parsedSource["Error"]);
        }
        return new Inventory($$parsedSource as Partial<Inventory>);
    }
}

export class LightingSnapshot {
    "Pending": x6$1.LightingSelection;
    "Applied": x6$1.LightingSelection | null;
    "Effects": x6$1.LightingEffect[];
    "Revision": number;
    "Firmware": string;
    "Error": Error;

    /** Creates a new LightingSnapshot instance. */
    constructor($$source: Partial<LightingSnapshot> = {}) {
        if (!("Pending" in $$source)) {
            this["Pending"] = (new x6$1.LightingSelection());
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = null;
        }
        if (!("Effects" in $$source)) {
            this["Effects"] = [];
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LightingSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): LightingSnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField0_0($$parsedSource["Pending"]);
        }
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField1_0($$parsedSource["Applied"]);
        }
        if ("Effects" in $$parsedSource) {
            $$parsedSource["Effects"] = $$createField2_0($$parsedSource["Effects"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField5_0($$parsedSource["Error"]);
        }
        return new LightingSnapshot($$parsedSource as Partial<LightingSnapshot>);
    }
}

/**
 * MacroDraft is one local assignment, not a firmware slot inventory. Events are
 * frozen at staging; later library edits require explicit restaging.
 */
export class MacroDraft {
    "ID": string;
    "Name": string;
    "Button": number;
    "Repeat": number;
    "Events": macros$0.Event[];

    /** Creates a new MacroDraft instance. */
    constructor($$source: Partial<MacroDraft> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Button" in $$source)) {
            this["Button"] = 0;
        }
        if (!("Repeat" in $$source)) {
            this["Repeat"] = 0;
        }
        if (!("Events" in $$source)) {
            this["Events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacroDraft instance from a string or object.
     */
    static createFrom($$source: any = {}): MacroDraft {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Events" in $$parsedSource) {
            $$parsedSource["Events"] = $$createField3_0($$parsedSource["Events"]);
        }
        return new MacroDraft($$parsedSource as Partial<MacroDraft>);
    }
}

export class NormalSleepSnapshot {
    "Pending": number;
    "Applied": number;
    "Persisted": number | null;
    "Revision": number;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;
    "Error": Error;

    /** Creates a new NormalSleepSnapshot instance. */
    constructor($$source: Partial<NormalSleepSnapshot> = {}) {
        if (!("Pending" in $$source)) {
            this["Pending"] = 0;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = 0;
        }
        if (!("Persisted" in $$source)) {
            this["Persisted"] = null;
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NormalSleepSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): NormalSleepSnapshot {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField5_0($$parsedSource["Error"]);
        }
        return new NormalSleepSnapshot($$parsedSource as Partial<NormalSleepSnapshot>);
    }
}

export class PollingSnapshot {
    "Desired": x6$1.PollingRate;
    "Applied": x6$1.PollingRate;
    "Persisted": x6$1.PollingRate | null;
    "Factory": x6$1.PollingRate;
    "Revision": number;
    "Error": Error;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;

    /** Creates a new PollingSnapshot instance. */
    constructor($$source: Partial<PollingSnapshot> = {}) {
        if (!("Desired" in $$source)) {
            this["Desired"] = x6$0.PollingRate.$zero;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = x6$0.PollingRate.$zero;
        }
        if (!("Persisted" in $$source)) {
            this["Persisted"] = null;
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = x6$0.PollingRate.$zero;
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollingSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): PollingSnapshot {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField4_0($$parsedSource["Error"]);
        }
        return new PollingSnapshot($$parsedSource as Partial<PollingSnapshot>);
    }
}

export class RemapSnapshot {
    "MacroPending": MacroDraft | null;
    "MacroApplied": MacroDraft | null;
    "MacroProgress": mouse$0.MacroProgress;
    "Pending": x6$1.RemapConfig;
    "Applied": x6$1.RemapConfig;
    "Factory": x6$1.RemapConfig;
    "Actions": x6$1.RemapAction[];
    "Revision": number;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;
    "Error": Error;

    /** Creates a new RemapSnapshot instance. */
    constructor($$source: Partial<RemapSnapshot> = {}) {
        if (!("MacroPending" in $$source)) {
            this["MacroPending"] = null;
        }
        if (!("MacroApplied" in $$source)) {
            this["MacroApplied"] = null;
        }
        if (!("MacroProgress" in $$source)) {
            this["MacroProgress"] = (new mouse$0.MacroProgress());
        }
        if (!("Pending" in $$source)) {
            this["Pending"] = (new x6$1.RemapConfig());
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = (new x6$1.RemapConfig());
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = (new x6$1.RemapConfig());
        }
        if (!("Actions" in $$source)) {
            this["Actions"] = [];
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemapSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): RemapSnapshot {
        const $$createField0_0 = $$createType12;
        const $$createField0_1 = $$createType12;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType14;
        const $$createField2_1 = $$createType14;
        const $$createField2_2 = $$createType14;
        const $$createField3_0 = $$createType15;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("MacroPending" in $$parsedSource) {
            $$parsedSource["MacroPending"] = $$createField0_0($$parsedSource["MacroPending"]);
        }
        if ("MacroApplied" in $$parsedSource) {
            $$parsedSource["MacroApplied"] = $$createField0_1($$parsedSource["MacroApplied"]);
        }
        if ("MacroProgress" in $$parsedSource) {
            $$parsedSource["MacroProgress"] = $$createField1_0($$parsedSource["MacroProgress"]);
        }
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField2_0($$parsedSource["Pending"]);
        }
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField2_1($$parsedSource["Applied"]);
        }
        if ("Factory" in $$parsedSource) {
            $$parsedSource["Factory"] = $$createField2_2($$parsedSource["Factory"]);
        }
        if ("Actions" in $$parsedSource) {
            $$parsedSource["Actions"] = $$createField3_0($$parsedSource["Actions"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField7_0($$parsedSource["Error"]);
        }
        return new RemapSnapshot($$parsedSource as Partial<RemapSnapshot>);
    }
}

export class ResetLaneResult {
    "Lane": string;
    "State": string;
    "Code": ErrorCode;

    /** Creates a new ResetLaneResult instance. */
    constructor($$source: Partial<ResetLaneResult> = {}) {
        if (!("Lane" in $$source)) {
            this["Lane"] = "";
        }
        if (!("State" in $$source)) {
            this["State"] = "";
        }
        if (!("Code" in $$source)) {
            this["Code"] = ErrorCode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetLaneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetLaneResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetLaneResult($$parsedSource as Partial<ResetLaneResult>);
    }
}

export class ResetResult {
    "Lanes": ResetLaneResult[];
    "Cleanup": ResetLaneResult;
    "Error": Error;
    "RetryAvailable": boolean;

    /** Creates a new ResetResult instance. */
    constructor($$source: Partial<ResetResult> = {}) {
        if (!("Lanes" in $$source)) {
            this["Lanes"] = [];
        }
        if (!("Cleanup" in $$source)) {
            this["Cleanup"] = (new ResetLaneResult());
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetResult {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType16;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Lanes" in $$parsedSource) {
            $$parsedSource["Lanes"] = $$createField0_0($$parsedSource["Lanes"]);
        }
        if ("Cleanup" in $$parsedSource) {
            $$parsedSource["Cleanup"] = $$createField1_0($$parsedSource["Cleanup"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField2_0($$parsedSource["Error"]);
        }
        return new ResetResult($$parsedSource as Partial<ResetResult>);
    }
}

export class Service {

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

export class Snapshot {
    "Connection": string;
    "Battery": number | null;
    "Applied": DPIConfig;
    "Pending": DPIConfig;
    "Factory": DPIConfig;
    "Revision": number;
    "Error": Error;
    "Firmware": string;
    "Persistence": string;
    "RetryAvailable": boolean;
    "ObservedStage": number | null;
    "ObservedDPI": number | null;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("Connection" in $$source)) {
            this["Connection"] = "";
        }
        if (!("Battery" in $$source)) {
            this["Battery"] = null;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = (new DPIConfig());
        }
        if (!("Pending" in $$source)) {
            this["Pending"] = (new DPIConfig());
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = (new DPIConfig());
        }
        if (!("Revision" in $$source)) {
            this["Revision"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = (new Error());
        }
        if (!("Firmware" in $$source)) {
            this["Firmware"] = "";
        }
        if (!("Persistence" in $$source)) {
            this["Persistence"] = "";
        }
        if (!("RetryAvailable" in $$source)) {
            this["RetryAvailable"] = false;
        }
        if (!("ObservedStage" in $$source)) {
            this["ObservedStage"] = null;
        }
        if (!("ObservedDPI" in $$source)) {
            this["ObservedDPI"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField2_0 = $$createType18;
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType18;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField2_0($$parsedSource["Applied"]);
        }
        if ("Pending" in $$parsedSource) {
            $$parsedSource["Pending"] = $$createField3_0($$parsedSource["Pending"]);
        }
        if ("Factory" in $$parsedSource) {
            $$parsedSource["Factory"] = $$createField4_0($$parsedSource["Factory"]);
        }
        if ("Error" in $$parsedSource) {
            $$parsedSource["Error"] = $$createField6_0($$parsedSource["Error"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

/**
 * StatusListener runs the always-on status listener until its context is
 * cancelled, forwarding every dongle-pushed report through onStatus.
 */
export type StatusListener = any;

/**
 * UpdateInfo is the display-only update contract exported to Wails bindings.
 */
export class UpdateInfo {
    "Version": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export type resetRunner = any;

// Private type creation functions
const $$createType0 = Error.createFrom;
const $$createType1 = mouse$0.Device.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = mouse$0.Binding.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = x6$0.LightingSelection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = x6$1.LightingEffect.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = macros$0.Event.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = MacroDraft.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = mouse$0.MacroProgress.createFrom;
const $$createType14 = x6$0.RemapConfig.createFrom;
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = ResetLaneResult.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = DPIConfig.createFrom;
