// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mouse$0 from "../mouse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$1 from "../protocol/x6/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x6$0 from "../x6/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyDPI(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3461389201).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApplyLighting writes the staged catalog vector through one validated binding.
 */
export function ApplyLighting(): $CancellablePromise<$models.LightingSnapshot> {
    return $Call.ByID(2699165782).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ApplyPollingRate writes the selected pending polling rate after explicit user confirmation.
 */
export function ApplyPollingRate(): $CancellablePromise<$models.PollingSnapshot> {
    return $Call.ByID(3669795219).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ApplyRemap validates and writes one complete draft. Applied state advances
 * only after the targeted command receives its ACK.
 */
export function ApplyRemap(config: x6$0.RemapConfig): $CancellablePromise<$models.RemapSnapshot> {
    return $Call.ByID(4250088139, config).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * AttachDevicePersistence wires keyed selected-device applied-state storage.
 */
export function AttachDevicePersistence(load: any, save: any): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(3887596840, load, save).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * AttachInventory wires the targeted device service used for explicit desktop selection.
 */
export function AttachInventory(inventory: mouse$0.TargetedService | null): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(3655060073, inventory).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * AttachListener wires the always-on status listener and the frontend event
 * sink. It does not start listening; call StartListener with a context.
 */
export function AttachListener(listener: $models.StatusListener, events: $models.EventSink): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(3795100807, listener, events).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * AttachMigrator wires backup-first legacy migration to a selected device.
 */
export function AttachMigrator(migrate: any): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(1213464496, migrate).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AttachPollingPersistence(load: any, save: any): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(46337553, load, save).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * AttachResetRunner wires the reset orchestration shared by desktop and CLI entrypoints.
 */
export function AttachResetRunner(runner: $models.resetRunner): $CancellablePromise<$models.Service | null> {
    return $Call.ByID(2710634656, runner).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetLightingSnapshot reports staged and acknowledged lighting state without
 * claiming a live hardware read.
 */
export function GetLightingSnapshot(): $CancellablePromise<$models.LightingSnapshot> {
    return $Call.ByID(1849424142).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPollingSnapshot reports desired, acknowledged, and persistence state; it
 * deliberately does not claim a live hardware observation.
 */
export function GetPollingSnapshot(): $CancellablePromise<$models.PollingSnapshot> {
    return $Call.ByID(1825488429).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRemapSnapshot reports local remap truth; the device has no remap readback.
 */
export function GetRemapSnapshot(): $CancellablePromise<$models.RemapSnapshot> {
    return $Call.ByID(3043747887).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSnapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(152452614).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Quiesce cancels scheduled DPI and polling writes and invalidates their captured
 * revisions before a reset writes the same selected device.
 */
export function Quiesce(binding: $models.Binding): $CancellablePromise<void> {
    return $Call.ByID(2160581423, binding);
}

/**
 * RefreshInventory exposes all discovered devices and the explicit selection.
 */
export function RefreshInventory(): $CancellablePromise<$models.Inventory> {
    return $Call.ByID(2420989727).then(($result: any) => {
        return $$createType6($result);
    });
}

export function RefreshStatus(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3077675599).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetToFactory delegates one explicitly confirmed reset to the shared runner.
 */
export function ResetToFactory(): $CancellablePromise<$models.ResetResult> {
    return $Call.ByID(2708725118).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RetryPersistence(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(808566931).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RetryPollingPersistence(): $CancellablePromise<$models.PollingSnapshot> {
    return $Call.ByID(3085626362).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RetryRemapPersistence(): $CancellablePromise<$models.RemapSnapshot> {
    return $Call.ByID(2964542300).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SelectDevice establishes an explicit binding for a previously inventoried device.
 */
export function SelectDevice(id: $models.DeviceID): $CancellablePromise<$models.Inventory> {
    return $Call.ByID(236647672, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StageDPI(config: $models.DPIConfig): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2647292463, config).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StageLighting updates only the selected device's pending state.
 */
export function StageLighting(selection: x6$0.LightingSelection): $CancellablePromise<$models.LightingSnapshot> {
    return $Call.ByID(1205871004, selection).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StagePollingRate(rate: x6$0.PollingRate): $CancellablePromise<$models.PollingSnapshot> {
    return $Call.ByID(1822189569, rate).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StartListener runs the status listener until ctx is cancelled, forwarding
 * every dongle-pushed status report into the service state and the frontend.
 * It is a no-op when no listener has been attached.
 */
export function StartListener(): $CancellablePromise<void> {
    return $Call.ByID(987205650);
}

// Private type creation functions
const $$createType0 = $models.Snapshot.createFrom;
const $$createType1 = $models.LightingSnapshot.createFrom;
const $$createType2 = $models.PollingSnapshot.createFrom;
const $$createType3 = $models.RemapSnapshot.createFrom;
const $$createType4 = $models.Service.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.Inventory.createFrom;
const $$createType7 = $models.ResetResult.createFrom;
